-- AlterTable
ALTER TABLE "Reading" ALTER COLUMN "timestamp_utc" DROP NOT NULL,
ALTER COLUMN "datetime" DROP NOT NULL,
ALTER COLUMN "tz_offset" DROP NOT NULL,
ALTER COLUMN "value" DROP NOT NULL,
ALTER COLUMN "precision" DROP NOT NULL,
ALTER COLUMN "mrid" DROP NOT NULL,
ALTER COLUMN "error_flag" DROP NOT NULL;

-- AlterTable
ALTER TABLE "SensorData" ALTER COLUMN "sensor_sn" DROP NOT NULL,
ALTER COLUMN "sensor_name" DROP NOT NULL,
ALTER COLUMN "units" DROP NOT NULL,
ALTER COLUMN "depth" DROP NOT NULL;
